trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: GitHubPush@0
  inputs:
    repositoryName: 'crossplane-gitops'
    target: 'refs/heads/main'
    filepath: 'ado-ec2.yaml'
    contents: 'This is an example file.'
    oauthToken: '$(GITHUB_TOKEN)'
