# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github crossplane 1'
    repositoryName: 'marikb/crossplane-gitops'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: '$(Build.ArtifactStagingDirectory)/Devops-ec2.yaml'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'