# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "
      apiVersion: v1
      kind: Pod
      metadata:
        name: ec2-instance
      spec:
        containers:
        - name: ec2-instance
          image: amazonlinux:latest
          command: ["/bin/bash"]
          args: ["-c", "while true; do sleep 1; done"]
      " > Devops-Ec2.yaml
- task: GitHub@1
  inputs:
    connection: 'GitHub connection' # The connection to your GitHub account
    repositoryName: 'marikb/crossplane-gitops'
    action: 'createOrUpdateReleaseAsset'
    assetType: 'yaml' # The type of asset to upload
    releaseTag: '1'
    assetName: 'Devops-Ec2.yaml' # The name of the file to upload
    assetPath: './Devops-Ec2.yaml' # The local path of the file to upload
