apiVersion: eks.aws.upbound.io/v1beta1
kind: IdentityProviderConfig
metadata:
  annotations:
    uptest.upbound.io/timeout: "3600" # one hour timeout
  name: example
spec:
  forProvider:
    region: us-west-1
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    oidc:
    - clientId: test-audience
      issuerUrl: https://issuer.url
